version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: oide_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: oide_conference_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
